//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.Fundamental.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.Fundamental.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depotkonto.
        /// </summary>
        internal static string BankStatement_BankAccount {
            get {
                return ResourceManager.GetString("BankStatement_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Währung.
        /// </summary>
        internal static string BankStatement_Currency {
            get {
                return ResourceManager.GetString("BankStatement_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marktwert in EUR inkl. Stückzinsen.
        /// </summary>
        internal static string BankStatement_CurrentValueInEuro {
            get {
                return ResourceManager.GetString("BankStatement_CurrentValueInEuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand.
        /// </summary>
        internal static string BankStatement_Nominal {
            get {
                return ResourceManager.GetString("BankStatement_Nominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurs.
        /// </summary>
        internal static string BankStatement_PriceInCurrency {
            get {
                return ResourceManager.GetString("BankStatement_PriceInCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezeichnung.
        /// </summary>
        internal static string BankStatement_SecurityName {
            get {
                return ResourceManager.GetString("BankStatement_SecurityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKN.
        /// </summary>
        internal static string BankStatement_SecurityNumber {
            get {
                return ResourceManager.GetString("BankStatement_SecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes undone.
        /// </summary>
        internal static string ChangesUndone {
            get {
                return ResourceManager.GetString("ChangesUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import file &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotImportFile {
            get {
                return ResourceManager.GetString("CouldNotImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read nominal or quote for security {0}.
        /// </summary>
        internal static string CouldNotReadNominalOrPriceFor {
            get {
                return ResourceManager.GetString("CouldNotReadNominalOrPriceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not split: {0}.
        /// </summary>
        internal static string CouldNotSplit {
            get {
                return ResourceManager.GetString("CouldNotSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved.
        /// </summary>
        internal static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date could not be extracted from file name.
        /// </summary>
        internal static string DateCouldNotBeExtractedFromFileName {
            get {
                return ResourceManager.GetString("DateCouldNotBeExtractedFromFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date tag {0} not found.
        /// </summary>
        internal static string DateTagNotFound {
            get {
                return ResourceManager.GetString("DateTagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security is empty.
        /// </summary>
        internal static string EmptySecurity {
            get {
                return ResourceManager.GetString("EmptySecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File imported, see log.
        /// </summary>
        internal static string FileImported {
            get {
                return ResourceManager.GetString("FileImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; imported ({1} record(s), {2} added, {3} updated) and moved to the folder &apos;Done&apos;.
        /// </summary>
        internal static string FileImportedAndMoved {
            get {
                return ResourceManager.GetString("FileImportedAndMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too small.
        /// </summary>
        internal static string FileTooSmall {
            get {
                return ResourceManager.GetString("FileTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found new import file &apos;{0}&apos;.
        /// </summary>
        internal static string FoundNewFile {
            get {
                return ResourceManager.GetString("FoundNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote value development for security {0} ({1}).
        /// </summary>
        internal static string HoldingsPerSecurityChartTitle {
            get {
                return ResourceManager.GetString("HoldingsPerSecurityChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import File.
        /// </summary>
        internal static string ImportCommandName {
            get {
                return ResourceManager.GetString("ImportCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing &apos;{0}&apos;.
        /// </summary>
        internal static string ImportingFile {
            get {
                return ResourceManager.GetString("ImportingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} quotes imported, {1} warning(s)/error(s).
        /// </summary>
        internal static string ImportResult {
            get {
                return ResourceManager.GetString("ImportResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read date: {0}.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read price: {0}.
        /// </summary>
        internal static string InvalidPrice {
            get {
                return ResourceManager.GetString("InvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key word {0} not found.
        /// </summary>
        internal static string KeyWordNotFound {
            get {
                return ResourceManager.GetString("KeyWordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; distributed to environments and deleted.
        /// </summary>
        internal static string NewFileSpreadThenDeleted {
            get {
                return ResourceManager.GetString("NewFileSpreadThenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough data: {0}.
        /// </summary>
        internal static string NotEnoughData {
            get {
                return ResourceManager.GetString("NotEnoughData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Quotes_Dump_Date {
            get {
                return ResourceManager.GetString("Quotes_Dump_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Quotes_Dump_PriceInEuro {
            get {
                return ResourceManager.GetString("Quotes_Dump_PriceInEuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Quotes_Dump_SecurityId {
            get {
                return ResourceManager.GetString("Quotes_Dump_SecurityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Chart.
        /// </summary>
        internal static string RefreshChartCommandName {
            get {
                return ResourceManager.GetString("RefreshChartCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshContextCommandName {
            get {
                return ResourceManager.GetString("RefreshContextCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative summary.
        /// </summary>
        internal static string RelativeSummaryChartTitle {
            get {
                return ResourceManager.GetString("RelativeSummaryChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveCommandName {
            get {
                return ResourceManager.GetString("SaveCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursfaktor.
        /// </summary>
        internal static string Securities_Dump_QuotedPer {
            get {
                return ResourceManager.GetString("Securities_Dump_QuotedPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKN.
        /// </summary>
        internal static string Securities_Dump_SecurityId {
            get {
                return ResourceManager.GetString("Securities_Dump_SecurityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezeichnung.
        /// </summary>
        internal static string Securities_Dump_SecurityName {
            get {
                return ResourceManager.GetString("Securities_Dump_SecurityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security {0} is quoted in {1}.
        /// </summary>
        internal static string SecurityIsQuotedIn {
            get {
                return ResourceManager.GetString("SecurityIsQuotedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string SummaryChartTitle {
            get {
                return ResourceManager.GetString("SummaryChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Transactions_Dump_Date {
            get {
                return ResourceManager.GetString("Transactions_Dump_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss.
        /// </summary>
        internal static string Transactions_Dump_Loss {
            get {
                return ResourceManager.GetString("Transactions_Dump_Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal.
        /// </summary>
        internal static string Transactions_Dump_Nominal {
            get {
                return ResourceManager.GetString("Transactions_Dump_Nominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Transactions_Dump_PriceInEuro {
            get {
                return ResourceManager.GetString("Transactions_Dump_PriceInEuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        internal static string Transactions_Dump_Profit {
            get {
                return ResourceManager.GetString("Transactions_Dump_Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Transactions_Dump_SecurityId {
            get {
                return ResourceManager.GetString("Transactions_Dump_SecurityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Transactions_Dump_Type {
            get {
                return ResourceManager.GetString("Transactions_Dump_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string UndoCommandName {
            get {
                return ResourceManager.GetString("UndoCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find security: {0}.
        /// </summary>
        internal static string UnknownSecurity {
            get {
                return ResourceManager.GetString("UnknownSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving imported quotes to the database.
        /// </summary>
        internal static string WriteImportedQuotes {
            get {
                return ResourceManager.GetString("WriteImportedQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving imported securities to the database.
        /// </summary>
        internal static string WriteImportedSecurities {
            get {
                return ResourceManager.GetString("WriteImportedSecurities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving imported transactions to the database.
        /// </summary>
        internal static string WriteImportedTransactions {
            get {
                return ResourceManager.GetString("WriteImportedTransactions", resourceCulture);
            }
        }
    }
}
